# Generated by Django 2.2.8 on 2020-01-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0006_auto_20181022_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.CharField(max_length=400),
        ),
    ]
