# Generated by Django 2.2.8 on 2020-01-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0007_auto_20200111_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='screenshot',
            new_name='cover',
        ),
    ]
